# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    parse_branch_index: true
    _icon: 'wysiwyg'
    _enabled_editors:
      - visual
      - content
    schemas:
      page:
        path: schemas/pages.md
    filter:
      base: strict
      exclude:
        - components.md
        - posts/_index.md
        - projects/_index.md
  projects:
    output: true
    _enabled_editors:
      - content
      - visual
    _icon: 'work_outline'
    schemas:
      default:
        path: schemas/projects.md
  testimonials:
    output: false
    preview:
      icon: 'format_quote'
      gallery: 
        image:
          - key: 'image'
        fit: contain
      subtext: 
        - key: 'position'
    _icon: 'format_quote'
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/testimonials.md
  posts:
    output: true
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: schemas/posts.md



# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC

_structures:
  content_blocks:
    style: modal
